background_opacity 0.4

# sei n em
cursor_trail 1
cursor_shape beam
cursor_beam_thickness 10

# Fonte principal
font_family "JetBrainsMono Nerd Font"
font_size 11

# Fontes fallback (para símbolos/emoji/japonês)
# Esses são exemplos, você pode ajustar
symbol_map U+1F300-U+1FAFF "Noto Color Emoji"
symbol_map U+3000-U+30FF "Noto Sans CJK JP"